export const FETCH_COUNTRIES_START = "FETCH_COUNTRIES_START";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAILED = "FETCH_COUNTRIES_FAILED";

export const FETCH_CONVERSION_START = "FETCH_CONVERSION_START";
export const FETCH_CONVERSION_SUCCESS = "FETCH_CONVERSION_SUCCESS";
export const FETCH_CONVERSION_FAILED = "FETCH_CONVERSION_FAILED";

export const FETCH_HISTORICAL_RATES_START = "FETCH_HISTORICAL_RATES_START";
export const FETCH_HISTORICAL_RATES_SUCCESS = "FETCH_HISTORICAL_RATES_SUCCESS";
export const FETCH_HISTORICAL_RATES_FAILED = "FETCH_HISTORICAL_RATES_FAILED";
